-- =============================================================================
-- GUÍA Y SCRIPT DE IMPLEMENTACIÓN DE ENDPOINTS REST EN ORACLE ORDS
-- Esquema Objetivo: SIS_SANLUISCLOUD
-- Módulo ORDS: mobile
-- Descripción: Paquete PL/SQL 'pkg_preventas_mobile' y registro de Handlers REST
--              para Condiciones de Venta, Faltantes y Sincronización Diaria.
-- =============================================================================

SET DEFINE OFF;

--------------------------------------------------------------------------------
-- 1. PERMISOS REQUERIDOS (Ejecutar con usuario SYS / SYSTEM si es necesario)
--------------------------------------------------------------------------------
/*
GRANT EXECUTE ON ORDS TO SIS_SANLUISCLOUD;
GRANT EXECUTE ON APEX_JSON TO SIS_SANLUISCLOUD;
GRANT EXECUTE ON APEX_JWT TO SIS_SANLUISCLOUD;
*/

--------------------------------------------------------------------------------
-- 2. DDL DE TABLAS REFERENCIALES (Si no existen en el esquema)
--------------------------------------------------------------------------------

-- Tabla de Condiciones de Venta
CREATE TABLE SIS_SANLUISCLOUD.vtas_condiciones_venta (
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    sisorg_id       NUMBER NOT NULL,
    codigo          VARCHAR2(10) NOT NULL,
    descripcion     VARCHAR2(100) NOT NULL,
    dias_plazo      NUMBER DEFAULT 0,
    activo          VARCHAR2(1) DEFAULT 'S' CHECK (activo IN ('S', 'N')),
    fecha_creacion  DATE DEFAULT SYSDATE,
    fecha_modifica  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_vtas_cond_venta PRIMARY KEY (id),
    CONSTRAINT uk_vtas_cond_cod UNIQUE (sisorg_id, codigo)
);

-- Inserción de datos iniciales comunes
INSERT INTO SIS_SANLUISCLOUD.vtas_condiciones_venta (sisorg_id, codigo, descripcion, dias_plazo, activo)
SELECT 14, 'CNT', 'CONTADO', 0, 'S' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SIS_SANLUISCLOUD.vtas_condiciones_venta WHERE sisorg_id = 14 AND codigo = 'CNT');

INSERT INTO SIS_SANLUISCLOUD.vtas_condiciones_venta (sisorg_id, codigo, descripcion, dias_plazo, activo)
SELECT 14, 'CC', 'CUENTA CORRIENTE', 30, 'S' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SIS_SANLUISCLOUD.vtas_condiciones_venta WHERE sisorg_id = 14 AND codigo = 'CC');

COMMIT;

-- Tabla de Productos Faltantes Reportados
CREATE TABLE SIS_SANLUISCLOUD.pre_faltantes (
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    sisorg_id       NUMBER NOT NULL,
    vendedor_id     NUMBER,
    deposito_id     NUMBER,
    producto_id     NUMBER NOT NULL,
    fecha           VARCHAR2(30),
    observacion     VARCHAR2(500),
    estado          VARCHAR2(20) DEFAULT 'ACTIVO',
    fecha_registro  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_pre_faltantes PRIMARY KEY (id)
);

--------------------------------------------------------------------------------
-- 3. ESPECIFICACIÓN DEL PAQUETE PL/SQL: pkg_preventas_mobile
--------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE SIS_SANLUISCLOUD.pkg_preventas_mobile AS

    /**
     * Retorna cursor con las condiciones de venta activas de la organización.
     */
    FUNCTION f_get_condiciones_venta (
        p_sisorg_id IN NUMBER
    ) RETURN SYS_REFCURSOR;

    /**
     * Retorna cursor con los productos faltantes reportados con paginación.
     */
    FUNCTION f_get_faltantes (
        p_sisorg_id   IN NUMBER,
        p_deposito_id IN NUMBER DEFAULT NULL,
        p_vendedor_id IN NUMBER DEFAULT NULL,
        p_limit       IN NUMBER DEFAULT 50,
        p_offset      IN NUMBER DEFAULT 0
    ) RETURN SYS_REFCURSOR;

    /**
     * Retorna cursor con clientes activos con soporte para sincronización delta.
     */
    FUNCTION f_get_clientes_sync (
        p_sisorg_id          IN NUMBER,
        p_vendedor_id        IN NUMBER DEFAULT NULL,
        p_actualizado_desde  IN TIMESTAMP WITH TIME ZONE DEFAULT NULL,
        p_limit              IN NUMBER DEFAULT 500,
        p_offset             IN NUMBER DEFAULT 0
    ) RETURN SYS_REFCURSOR;

END pkg_preventas_mobile;
/

--------------------------------------------------------------------------------
-- 4. CUERPO DEL PAQUETE PL/SQL: pkg_preventas_mobile
--------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY SIS_SANLUISCLOUD.pkg_preventas_mobile AS

    FUNCTION f_get_condiciones_venta (
        p_sisorg_id IN NUMBER
    ) RETURN SYS_REFCURSOR IS
        v_cur SYS_REFCURSOR;
    BEGIN
        OPEN v_cur FOR
            SELECT id          AS condicion_id,
                   codigo      AS codigo,
                   descripcion AS descripcion,
                   dias_plazo  AS dias_plazo,
                   activo      AS activo
              FROM vtas_condiciones_venta
             WHERE sisorg_id = p_sisorg_id
               AND activo = 'S'
             ORDER BY codigo ASC;
        RETURN v_cur;
    END f_get_condiciones_venta;

    FUNCTION f_get_faltantes (
        p_sisorg_id   IN NUMBER,
        p_deposito_id IN NUMBER DEFAULT NULL,
        p_vendedor_id IN NUMBER DEFAULT NULL,
        p_limit       IN NUMBER DEFAULT 50,
        p_offset      IN NUMBER DEFAULT 0
    ) RETURN SYS_REFCURSOR IS
        v_cur SYS_REFCURSOR;
    BEGIN
        OPEN v_cur FOR
            SELECT f.id,
                   f.producto_id,
                   NVL(p.codigo, TO_CHAR(f.producto_id)) AS codigo,
                   NVL(p.descripcion, 'PRODUCTO ' || f.producto_id) AS producto_descripcion,
                   f.fecha,
                   f.observacion,
                   f.estado
              FROM pre_faltantes f
              LEFT JOIN com_productos p ON p.id = f.producto_id
             WHERE f.sisorg_id = p_sisorg_id
               AND (p_deposito_id IS NULL OR f.deposito_id = p_deposito_id)
               AND (p_vendedor_id IS NULL OR f.vendedor_id = p_vendedor_id)
             ORDER BY f.id DESC
             OFFSET NVL(p_offset, 0) ROWS
             FETCH NEXT NVL(p_limit, 50) ROWS ONLY;
        RETURN v_cur;
    END f_get_faltantes;

    FUNCTION f_get_clientes_sync (
        p_sisorg_id          IN NUMBER,
        p_vendedor_id        IN NUMBER DEFAULT NULL,
        p_actualizado_desde  IN TIMESTAMP WITH TIME ZONE DEFAULT NULL,
        p_limit              IN NUMBER DEFAULT 500,
        p_offset             IN NUMBER DEFAULT 0
    ) RETURN SYS_REFCURSOR IS
        v_cur SYS_REFCURSOR;
    BEGIN
        OPEN v_cur FOR
            SELECT c.id               AS cliente_id,
                   c.codigo           AS codigo,
                   c.nombre           AS nombre,
                   c.razon_social     AS razon_social,
                   c.tipo_documento   AS tipo_documento,
                   c.numero_documento AS numero_documento,
                   c.tipo_iva         AS tipo_iva,
                   c.telefono         AS telefono,
                   c.email_principal  AS email_principal,
                   c.email_secundario AS email_secundario,
                   c.estado           AS estado,
                   c.localidad        AS localidad,
                   c.direccion        AS direccion,
                   c.geoposicion      AS geoposicion,
                   c.zona             AS zona,
                   c.vendedor_id      AS vendedor_id
              FROM vtas_clientes c
             WHERE c.sisorg_id = p_sisorg_id
               AND (p_vendedor_id IS NULL OR c.vendedor_id = p_vendedor_id)
               AND (p_actualizado_desde IS NULL OR c.fecha_modifica >= p_actualizado_desde)
             ORDER BY c.nombre ASC
             OFFSET NVL(p_offset, 0) ROWS
             FETCH NEXT NVL(p_limit, 500) ROWS ONLY;
        RETURN v_cur;
    END f_get_clientes_sync;

END pkg_preventas_mobile;
/

--------------------------------------------------------------------------------
-- 5. REGISTRO Y CONFIGURACIÓN DE HANDLERS Y PARÁMETROS EN ORDS
--------------------------------------------------------------------------------

BEGIN
    -- Asegurar que el módulo 'mobile' existe y está activo
    ORDS.DEFINE_MODULE(
        p_module_name    => 'mobile',
        p_base_path      => 'mobile/',
        p_items_per_page => 25,
        p_status         => 'PUBLISHED',
        p_comments       => 'Módulo de servicios REST para la App Móvil de Preventas'
    );

    -- =========================================================================
    -- ENDPOINT 1: GET mobile/condiciones-venta
    -- =========================================================================
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'mobile',
        p_pattern        => 'condiciones-venta',
        p_comments       => 'Consulta de Condiciones de Venta para pedidos'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'mobile',
        p_pattern        => 'condiciones-venta',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    v_cur       SYS_REFCURSOR;
    v_org_id    NUMBER := NVL(TO_NUMBER(:sisorg_id), 14);
BEGIN
    v_cur := pkg_preventas_mobile.f_get_condiciones_venta(p_sisorg_id => v_org_id);

    :status := 200;
    apex_json.open_object;
    apex_json.write(''items'', v_cur);
    apex_json.close_object;
EXCEPTION
    WHEN OTHERS THEN
        :status := 500;
        apex_json.open_object;
        apex_json.write(''success'', false);
        apex_json.write(''error'', SQLERRM);
        apex_json.close_object;
END;',
        p_comments       => 'Handler PL/SQL para retornar condiciones de venta'
    );

    -- Parámetro sisorg_id vía Header o Query
    ORDS.DEFINE_PARAMETER(
        p_module_name        => 'mobile',
        p_pattern            => 'condiciones-venta',
        p_method             => 'GET',
        p_name               => 'sisorg_id',
        p_bind_variable_name => 'sisorg_id',
        p_source_type        => 'HEADER',
        p_param_type         => 'STRING',
        p_access_method      => 'IN'
    );

    -- =========================================================================
    -- ENDPOINT 2: GET mobile/faltantes
    -- =========================================================================
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'mobile',
        p_pattern        => 'faltantes',
        p_comments       => 'Consulta de Productos Faltantes reportados'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'mobile',
        p_pattern        => 'faltantes',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    v_cur       SYS_REFCURSOR;
    v_org_id    NUMBER := NVL(TO_NUMBER(:sisorg_id), 14);
    v_dep_id    NUMBER := TO_NUMBER(:deposito_id);
    v_vend_id   NUMBER := TO_NUMBER(:vendedor_id);
    v_limit     NUMBER := NVL(TO_NUMBER(:limit), 50);
    v_offset    NUMBER := NVL(TO_NUMBER(:offset), 0);
BEGIN
    v_cur := pkg_preventas_mobile.f_get_faltantes(
        p_sisorg_id   => v_org_id,
        p_deposito_id => v_dep_id,
        p_vendedor_id => v_vend_id,
        p_limit       => v_limit,
        p_offset      => v_offset
    );

    :status := 200;
    apex_json.open_object;
    apex_json.write(''items'', v_cur);
    apex_json.write(''limit'', v_limit);
    apex_json.write(''offset'', v_offset);
    apex_json.close_object;
EXCEPTION
    WHEN OTHERS THEN
        :status := 500;
        apex_json.open_object;
        apex_json.write(''success'', false);
        apex_json.write(''error'', SQLERRM);
        apex_json.close_object;
END;',
        p_comments       => 'Handler PL/SQL para listar faltantes'
    );

    ORDS.DEFINE_PARAMETER(
        p_module_name        => 'mobile',
        p_pattern            => 'faltantes',
        p_method             => 'GET',
        p_name               => 'sisorg_id',
        p_bind_variable_name => 'sisorg_id',
        p_source_type        => 'HEADER',
        p_param_type         => 'STRING',
        p_access_method      => 'IN'
    );

    ORDS.DEFINE_PARAMETER(
        p_module_name        => 'mobile',
        p_pattern            => 'faltantes',
        p_method             => 'GET',
        p_name               => 'deposito_id',
        p_bind_variable_name => 'deposito_id',
        p_source_type        => 'QUERY',
        p_param_type         => 'STRING',
        p_access_method      => 'IN'
    );

    ORDS.DEFINE_PARAMETER(
        p_module_name        => 'mobile',
        p_pattern            => 'faltantes',
        p_method             => 'GET',
        p_name               => 'vendedor_id',
        p_bind_variable_name => 'vendedor_id',
        p_source_type        => 'QUERY',
        p_param_type         => 'STRING',
        p_access_method      => 'IN'
    );

    ORDS.DEFINE_PARAMETER(
        p_module_name        => 'mobile',
        p_pattern            => 'faltantes',
        p_method             => 'GET',
        p_name               => 'limit',
        p_bind_variable_name => 'limit',
        p_source_type        => 'QUERY',
        p_param_type         => 'INT',
        p_access_method      => 'IN'
    );

    ORDS.DEFINE_PARAMETER(
        p_module_name        => 'mobile',
        p_pattern            => 'faltantes',
        p_method             => 'GET',
        p_name               => 'offset',
        p_bind_variable_name => 'offset',
        p_source_type        => 'QUERY',
        p_param_type         => 'INT',
        p_access_method      => 'IN'
    );

    COMMIT;
END;
/

--------------------------------------------------------------------------------
-- 6. PRUEBAS DE VERIFICACIÓN CON CURL (Desde terminal o Postman)
--------------------------------------------------------------------------------
/*
# 1. Probar Condiciones de Venta:
curl -X GET "http://sanluiscloud.ddns.net/ords/sanluiscloud/mobile/condiciones-venta" \
     -H "Authorization: Bearer <TOKEN_JWT>" \
     -H "sisorg_id: 14"

# 2. Probar Consulta de Faltantes:
curl -X GET "http://sanluiscloud.ddns.net/ords/sanluiscloud/mobile/faltantes?limit=25&offset=0" \
     -H "Authorization: Bearer <TOKEN_JWT>" \
     -H "sisorg_id: 14"
*/
